### ISSUE TITLE
@media лучше использовать всегда в одну сторону

### ISSUE THREAD

**Issue by Znack** [Axent13/intern-maket-1#12]
Например, есть подход mobile first, дефолтные стили всегда пиши для мобилы, а в медиа пихай только для более широких экранов стили, соответственно все @media должны идти только по 
```
@media only screen and (min-width 1280px)
```
то есть только для широких экранов задаешь уточняющие стили

**Comment by Axent13** [comment]
Я правильно понял?
```
.some-class
  //mobile styles
  @media only screen and (min-width 1280px)
    //middle screen styles
  @media only screen and (min-width 1920px)
    //huge screen styles
```

**Comment by Znack** [comment]
Ага, но только не мобайл стили, а общие для всех, вообще всех мониторов)

чт, 10 нояб. 2016, 21:41 Axent13 <notifications@github.com>:
