### ISSUE TITLE
Не по стандарту шрифты

### ISSUE THREAD

**Issue by Znack** [Axent13/intern-maket-1#16]
font-family myriad_pro
И смысла особо в классах font-light и тд нет, там по сути можно просто font-weight менять. А то что в разметке доп класс для этого - лишь портит семантику)

**Comment by Axent13** [comment]
Смотрел видео на ютубе(когда еще только начинал макет верстать) что парень как раз так делал со шрифтами(т.е. font-light и т.п.), вот и тоже так сделал.)) Т.е. надо передать на вот так:
```
.example
  //тут всякие стили
  font-family myriadpro
  font-weight 500
.second-example
  //тут всякие стили
  font-family myriadpro
  font-weight 700
```
?

**Comment by Znack** [comment]
Font family у тебя вообще у корневого элемента указана должен быть, внутри
которого все элементы с таким шрифтом)
Останется только в стилях ширину шрифта менять и все)

чт, 10 нояб. 2016, 21:52 Axent13 <notifications@github.com>:
