### ISSUE TITLE
Компонент list надо сделать динамческим

### ISSUE THREAD

**Issue by Znack** [Axent13/intern-maket-1#20]
Сейчас этот компонент явный пример того, как делать компоненты никогда не стоит :)
Он целиком захаркожен для двух частных случаев, там эти два случая тупо дублируются, нет никакого API компоненты для ее параметризации ):

**Comment by Axent13** [comment]
Предлагаешь сделать так же, как я делал в Жизни?
```
drawField(cells) {
    const $gameField = $('.js-game-field');

    const locals = {
      fieldHeight: this._fieldHeight,
      fieldWidth: this._fieldWidth,
      cellsStates: cells,
    };

    $gameField.html(templateCreateCells(locals));

    this.emit('event');

    return $gameField.html();
  }
```
 Т.е. этот компонент list будет pug-шаблоном и из js-файла тогда брать данные(название уч.заведения/компании, период и т.д.). И потом опять же в js-файле этот компонент добавлять. Правильно мыслю?)

**Comment by Znack** [comment]
А зачем тут через js рендерить?) Нет, я тут совершенно не про это))

**Comment by Znack** [comment]
Кстати `this.emit('event');` лучше переименуй, тебе 5 секунд жалко придумать нормальное название?)

**Comment by Axent13** [comment]
А если так?

**Comment by Znack** [comment]
Да, примерно про это я и говорил :) Только я бы советовал не 5 разных аргументов списком передеавть, постоянно парясь о нужном порядке, а один аргумент кидать, в котором и будут свойства все нужные, то есть на входе будет один параметр примерно такой:
```
        {
            itemName: 'Master degree',
            itemNameColor: 'blue',
            periodStart: 'Feb 2011',
            periodEnd: 'Jun 2014',
            itemSubname: 'University name',
            itemText: 'Lorem ipsum'
        },
```

**Comment by Axent13** [comment]
Вот, теперь миксин **list** принимает один аргумент и потом сам из него свойства достает.

**Comment by Znack** [comment]
Вот, теперь стало значительно лучше :) Старайся все компоненты всегда примерно с таким API делать :)
