### ISSUE TITLE
Блок Software

### ISSUE THREAD

**Issue by HeyRoach** [Axent13/intern-maket-1#3]
По поводу линии прогресса. 
Переделать. Слишком громозко, попробовать найти другой вариант решения такой задачи.
Можно, например, добавить элемент внутри прогресса, указать ему в стилях синий цвет и уже в верстке задавать каждой линии свою ширину в процентах.
 В таком случае не нужен отдельный класс для каждой линии.

**Comment by Znack** [comment]
Это кстати обязательно, потому что верстка должна быть предназначена для динамического рендеринга - то есть сервер может брать эти данные из базы и вставлять в html, то есть нельзя такие динамические значения в css хардкодить. Для таких случаев в стандартах даже отдельно указано использовать инлайновые стили в качестве исключения
